package emailbomber.gui;

import emailbomber.network.AtaqueRemoto;
import emailbomber.network.AtaqueRemotoHandler;
import emailbomber.network.AtaqueRemotoDaemon;
import emailbomber.bomber.Bomber;
import emailbomber.bomber.BomberBatch;
import emailbomber.bomber.BomberParalelo;
import emailbomber.bomber.Email;
import emailbomber.network.ApiEstadoCliente;
import javax.swing.JOptionPane;

public class Ventana extends javax.swing.JFrame {

    private Bomber bomber;
    private JLabelEstadoConexion jLabelConexion;
    private AtaqueRemotoDaemon ataqueRemotoDaemon;
    private ApiEstadoCliente apiEstadoCliente;

    public Ventana() {
        initComponents();
        this.jLabelConexion = new JLabelEstadoConexion(this.aviso);
        this.jLabelConexion.start();
        setupAtaqueRemotoDaemon();
        this.ataqueRemotoDaemon.start();
        this.apiEstadoCliente = new ApiEstadoCliente("http://localhost:5000/api/estadocliente/", false);
    }

    private void setupAtaqueRemotoDaemon() {
        this.ataqueRemotoDaemon = new AtaqueRemotoDaemon(
                new AtaqueRemotoHandler() {
            @Override
            public void handleNuevoAtaque(AtaqueRemoto ataqueRemoto) {
                jLabelConexion.setEstado(JLabelEstadoConexion.estado.ATACANDO);
                if (bomber != null && !bomber.ataqueTerminado()) {
                    cancelarActionPerformed(null);
                    JOptionPane.showMessageDialog(
                            null,
                            "Ataque remoto recibido. Se debe cancelar ataque actual.",
                            "Mensaje",
                            JOptionPane.INFORMATION_MESSAGE
                    );
                }
                servidor.setText(ataqueRemoto.getUrlServidorAtacado());
                hilos.setValue(ataqueRemoto.getNumHilos());
                peticiones.setValue(ataqueRemoto.getNumIteraciones());
                if (ataqueRemoto.isEnParalelo()) {
                    paralelo.setSelected(true);
                } else {
                    batch.setSelected(true);
                }
                iniciarActionPerformed(null);
                cancelar.setEnabled(false);
            }

            @Override
            public void conexionEstablecida() {
                jLabelConexion.setEstado(JLabelEstadoConexion.estado.ESCUCHANDO);
            }

            @Override
            public void conexionPerdida() {
                jLabelConexion.setEstado(JLabelEstadoConexion.estado.NO_CONECTADO);
            }

            @Override
            public void abortarAtaqueRemoto() {
                cancelarActionPerformed(null);
            }
        },
                "http://localhost:5000/api/datosataque"
        );
    }

    private void setCamposEnabled(boolean estado) {
        this.remitente.setEnabled(estado);
        this.destinatario.setEnabled(estado);
        this.asunto.setEnabled(estado);
        this.mensaje.setEnabled(estado);
        this.hilos.setEnabled(estado);
        this.peticiones.setEnabled(estado);
        this.servidor.setEnabled(estado);
        this.paralelo.setEnabled(estado);
        this.batch.setEnabled(estado);
        this.datosAtaque.setEnabled(estado);
        this.estadoCliente.setEnabled(estado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.ButtonGroup buttonGroup2 = new javax.swing.ButtonGroup();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        destinatario = new javax.swing.JTextField();
        remitente = new javax.swing.JTextField();
        asunto = new javax.swing.JTextField();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        mensaje = new javax.swing.JTextArea();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        hilos = new javax.swing.JSpinner();
        peticiones = new javax.swing.JSpinner();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        servidor = new javax.swing.JTextField();
        paralelo = new javax.swing.JRadioButton();
        batch = new javax.swing.JRadioButton();
        iniciar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        servidoresRemotos1 = new emailbomber.gui.ServidoresRemotos();
        javax.swing.JPanel jPanel4 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        datosAtaque = new javax.swing.JTextField();
        aviso = new javax.swing.JLabel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        estadoCliente = new javax.swing.JTextField();
        javax.swing.JPanel jPanel5 = new javax.swing.JPanel();
        porcentaje = new javax.swing.JProgressBar();
        enviado = new javax.swing.JTextField();
        error = new javax.swing.JTextField();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));

        jLabel1.setText("Remitente:");

        jLabel2.setText("Destinatario:");

        jLabel3.setText("Asunto:");

        destinatario.setText("destinatario@mail.com");

        remitente.setText("remitente@mail.com");

        asunto.setText("Bomb");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Mensaje"));

        mensaje.setColumns(20);
        mensaje.setRows(1);
        mensaje.setText("qawsedrftgyhujik");
        jScrollPane1.setViewportView(mensaje);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(destinatario, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(remitente)
                    .addComponent(asunto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(remitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(destinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(asunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Ajustes"));

        jLabel4.setText("Hilos:");

        jLabel6.setText("Peticiones:");

        hilos.setModel(new javax.swing.SpinnerNumberModel(1, 1, 8, 1));

        peticiones.setModel(new javax.swing.SpinnerNumberModel(100, 1, 10000, 1));

        jLabel9.setText("Servidor:");

        servidor.setText("http://localhost:5000/api/email/");

        buttonGroup2.add(paralelo);
        paralelo.setSelected(true);
        paralelo.setText("Paralelo");

        buttonGroup2.add(batch);
        batch.setText("Por batch");

        iniciar.setText("Iniciar");
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.setEnabled(false);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hilos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(peticiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(servidor))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(paralelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(batch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(servidoresRemotos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(hilos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peticiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(servidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paralelo)
                    .addComponent(batch)
                    .addComponent(iniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(servidoresRemotos1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Ataque Remoto"));

        jLabel5.setText("Datos ataque:");

        datosAtaque.setText("http://localhost:5000/api/datosataque/");
        datosAtaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datosAtaqueActionPerformed(evt);
            }
        });

        aviso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emailbomber/gui/icons8-fire_alarm_button_3.png"))); // NOI18N
        aviso.setText(" ");

        jLabel8.setText("Estado cliente:");

        estadoCliente.setText("http://localhost:5000/api/estadocliente/");
        estadoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(estadoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(datosAtaque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aviso, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(datosAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aviso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(estadoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado"));

        enviado.setEditable(false);

        error.setEditable(false);

        jLabel10.setText("Error:");

        jLabel7.setText("Enviado:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(porcentaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enviado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(enviado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        setCamposEnabled(false);
        this.iniciar.setEnabled(false);
        this.cancelar.setEnabled(true);

        Email email = new Email();
        email.setRemitente(this.remitente.getText());
        email.setDestinatario(this.destinatario.getText());
        email.setSubject(this.asunto.getText());
        email.setBody(this.mensaje.getText());

        String urlServidor = this.servidor.getText();
        int numPeticiones = (int) this.peticiones.getValue();
        int numHilos = (int) this.hilos.getValue();

        if (this.paralelo.isSelected()) {
            this.bomber = new BomberParalelo(urlServidor, email, numHilos, numPeticiones);
        } else {
            this.bomber = new BomberBatch(urlServidor, email, numHilos, numPeticiones);
        }

        this.bomber.addUpdateListener(new SwingBomberUpdateListener(
                this.porcentaje,
                this.enviado,
                this.error,
                numPeticiones
        ));
        
        this.bomber.addUpdateListener((peticionesHechas, peticionesRechazadas) -> {
            this.apiEstadoCliente.updateEstadoAtaque(peticionesHechas, peticionesRechazadas);
        });

        boolean esAtaqueRemoto = evt == null;

        this.apiEstadoCliente.setEstadoAtacando(numPeticiones, esAtaqueRemoto);
        
        AtaqueRemoto ataqueRemoto = new AtaqueRemoto();
        ataqueRemoto.setNumHilos(numHilos);
        ataqueRemoto.setNumIteraciones(numPeticiones);
        ataqueRemoto.setUrlServidorAtacado(urlServidor);
        ataqueRemoto.setEnParalelo(this.paralelo.isSelected());
        this.servidoresRemotos1.enviarAtaque(ataqueRemoto);

        this.bomber.start();

        new Thread(() -> {
            while (!this.bomber.ataqueTerminado()) {
                try {
                    Thread.sleep(500);
                } catch (InterruptedException ex) {
                    ex.printStackTrace();
                }
            }
            setCamposEnabled(true);
            this.iniciar.setEnabled(true);
            this.cancelar.setEnabled(false);
            this.jLabelConexion.setEstado(JLabelEstadoConexion.estado.ESCUCHANDO);
            this.apiEstadoCliente.setEstadoAtaqueTerminado();
        }).start();

    }//GEN-LAST:event_iniciarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.bomber.abortar();
    }//GEN-LAST:event_cancelarActionPerformed

    private void datosAtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datosAtaqueActionPerformed
        this.ataqueRemotoDaemon.setUrlServidor(this.datosAtaque.getText());
    }//GEN-LAST:event_datosAtaqueActionPerformed

    private void estadoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoClienteActionPerformed
        this.apiEstadoCliente.setUrlServidor(this.estadoCliente.getText());
    }//GEN-LAST:event_estadoClienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField asunto;
    private javax.swing.JLabel aviso;
    private javax.swing.JRadioButton batch;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField datosAtaque;
    private javax.swing.JTextField destinatario;
    private javax.swing.JTextField enviado;
    private javax.swing.JTextField error;
    private javax.swing.JTextField estadoCliente;
    private javax.swing.JSpinner hilos;
    private javax.swing.JButton iniciar;
    private javax.swing.JTextArea mensaje;
    private javax.swing.JRadioButton paralelo;
    private javax.swing.JSpinner peticiones;
    private javax.swing.JProgressBar porcentaje;
    private javax.swing.JTextField remitente;
    private javax.swing.JTextField servidor;
    private emailbomber.gui.ServidoresRemotos servidoresRemotos1;
    // End of variables declaration//GEN-END:variables
}
